#!/bin/sh
# Usage: script/antlr
# Install and execute ANTLR Tool.

set -e

# Installs ANTLR
hash antlr4 2>/dev/null || brew install antlr

# Generates the Swift lexer, parser, and listener
pushd . >/dev/null
cd grammar
antlr4 -Dlanguage=Python3 Swift.g4 -o ../tailor/swift/
popd >/dev/null

# Removes ANTLR-generated tokens
rm tailor/swift/*.tokens

# Downcase reference to SwiftListener module in swiftparser.py
sed -i.bak 's/\.SwiftListener/\.swiftlistener/' tailor/swift/swiftparser.py
rm tailor/swift/swiftparser.py.bak
