#!/bin/sh
# Usage: script/antlr
# Installs and executes ANTLR Tool.

set -e

ANTLR_OUT="../src/main/java/com/sleekbyte/tailor/swift"
JAVA_PKG="com.sleekbyte.tailor.swift"

# Install ANTLR via Homebrew if nonexistent
hash antlr4 2>/dev/null || brew install antlr

# Generate the Swift lexer, parser, and listener
pushd . >/dev/null
cd grammar
antlr4 Swift.g4 -package "${JAVA_PKG}" -o "${ANTLR_OUT}"

# Remove ANTLR-generated tokens
rm "${ANTLR_OUT}"/*.tokens
popd >/dev/null
