#!/bin/sh
# Usage: script/bootstrap
# Installs python3, creates a virtualenv, and installs required modules for development.

set -e

# Install python3 via Homebrew if nonexistent
hash python3 2>/dev/null || brew install python3
# Create virtualenv if nonexistent
[[ -d venv ]] || pyvenv venv
# Activate virtualenv if deactivated
[[ -n $VIRTUAL_ENV ]] || { [[ -f venv/bin/activate ]] && source venv/bin/activate; }
# Update pip package manager
pip --quiet install --upgrade pip
# Install required development modules
pip --quiet install --requirement requirements-dev.txt
# Install Git pre-commit hooks using http://pre-commit.com
pre-commit install
pre-commit autoupdate
