#!/bin/sh
# Usage: script/cibuild
# Emulates a continuous integration build.

set -e

# Activate virtualenv if deactivated
[[ -n $VIRTUAL_ENV ]] || { [[ -f venv/bin/activate ]] && source venv/bin/activate; }
# Execute test script
script/test
# Run pre-commit hooks on all files
pre-commit run --all-files
