#!/usr/bin/env sh
# Usage: script/runhooks
# Run pre-commit hooks on all files.

set -e

# Activate virtualenv if deactivated
[ ${VIRTUAL_ENV} ] || { [ -f venv/bin/activate ] && source venv/bin/activate; }

# Run pre-commit hooks on all files
pre-commit run --all-files
