#!/bin/sh
# Usage: script/test
# Activates virtualenv and runs tests.

set -e

# Activate virtualenv if deactivated
[[ -n $VIRTUAL_ENV ]] || { [[ -f venv/bin/activate ]] && source venv/bin/activate; }
# Run tests in tailor/tests/
nosetests
